apiVersion: v1
kind: Service 
metadata:
  name: akka-service
  labels:
    app: akka-http
spec:
  type: NodePort
  selector:
    app: akka-http
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
...