apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-master
  labels:
    app: elasticsearch
spec:
  selector:
    component: elasticsearch
    role: master
  clusterIP: None
  ports:
    - port: 9200
      name: serving
    - port: 9300
      name: node-to-node
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-nodeport
  labels:
spec:
  selector:
    component: elasticsearch
    role: master
  type: NodePort
  ports:
    - port: 9200
      name: serving
      nodePort: 32000
    - port: 9300
      name: node-to-node
...