apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-0
  labels:
    app: elasticsearch
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: "elasticsearch-storage"
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - instance-4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-1
  labels:
    app: elasticsearch
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: "elasticsearch-storage"
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - instance-2
...